FROM eclipse-temurin:17-jdk-jammy
WORKDIR /workspace
COPY gradlew settings.gradle build.gradle ./
COPY gradle/ gradle/
COPY buildSrc/ buildSrc/
RUN chmod +x gradlew && ./gradlew --version --no-daemon
COPY . .
ENTRYPOINT ["./gradlew"]
CMD ["checkstyleMain", "checkstyleTest", "--continue", "--no-daemon", "--console=plain"]
