plugins {
	id 'aoi.plugin-conventions'
    id 'java'
}

description = 'Polymesh'

configurations {
  fatjar
}

dependencies {
    implementation project(':Translators')
    implementation libs.eventbus
    implementation libs.mtj
    fatjar libs.mtj
}

jar {
    from { configurations.fatjar.collect { it.isDirectory() ? it : zipTree(it) } }
}
