/* Copyright (C) 2023 by Maksim Khramov

 This program is free software; you can redistribute it and/or modify it under the
 terms of the GNU General Public License as published by the Free Software
 Foundation; either version 2 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful, but WITHOUT ANY
 WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 PARTICULAR PURPOSE.  See the GNU General Public License for more details. */

package artofillusion.preferences;

import artofillusion.ArtOfIllusion;
import artofillusion.ui.ThemeManager;
import artofillusion.ui.Translate;
import java.util.Comparator;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author MaksK
 */
@Slf4j
public class AppearancePreferencesPanelImpl extends javax.swing.JPanel {
    
    private static final Comparator<ThemeManager.ThemeInfo> tc  = Comparator.comparing(ThemeManager.ThemeInfo::getName);
    private final Locale[] languages = Translate.getAvailableLocales();
    /**
     * Creates new form AppearancePreferencesPanelImpl
     */
    public AppearancePreferencesPanelImpl() {
        initComponents();
    }

    private DefaultComboBoxModel<String> getLocalesModel() {
        var dcm = new DefaultComboBoxModel<String>();
        var cloc =  ArtOfIllusion.getPreferences().getLocale();
        for(Locale loc: languages) {
            var localeDisplayName = loc.getDisplayName(loc);
            dcm.addElement(localeDisplayName);
            if(cloc.equals(loc)) dcm.setSelectedItem(localeDisplayName);
        }
        return  dcm;
    } 
    
    private DefaultComboBoxModel<String> getThemesModel() {
        var dcm = new DefaultComboBoxModel<String>();
        var selectedThemeName = ThemeManager.getSelectedTheme().getName();
        ThemeManager.getThemes().stream().filter(info -> info.selectable).sorted(tc).forEach(theme -> {
            dcm.addElement(theme.getName());
            if(theme.getName().equals(selectedThemeName)) dcm.setSelectedItem(theme.getName());
        });
        return dcm;
    } 
      
    private DefaultComboBoxModel<String> getColorSetModel(ThemeManager.ThemeInfo theme) {
        var dcm = new DefaultComboBoxModel<String>();
        for(ThemeManager.ColorSet cSet:  theme.getColorSets()) {
            dcm.addElement(cSet.getName());
        } 
        return dcm;
    } 
    
    
    public Locale getSelectedLocale() {
        return languages[languageSelector.getSelectedIndex()];
    }

    public String getSelectedThemeName() {
        return themeSelector.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languageSelector = new javax.swing.JComboBox<>();
        javax.swing.JLabel languageLabel = new javax.swing.JLabel();
        themeSelector = new javax.swing.JComboBox<>();
        themeSelectorActionPerformed(null);
        javax.swing.JLabel themeLabel = new javax.swing.JLabel();
        colorSetSelector = new javax.swing.JComboBox<>();
        javax.swing.JLabel colorSetLabel = new javax.swing.JLabel();

        languageSelector.setMaximumRowCount(languages.length > 20 ? 16 : languages.length);
        languageSelector.setModel(getLocalesModel());

        languageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        languageLabel.setLabelFor(languageSelector);
        languageLabel.setText(Translate.text("language"));

        themeSelector.setModel(getThemesModel());
        themeSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeSelectorActionPerformed(evt);
            }
        });

        themeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        themeLabel.setText(Translate.text("selectedTheme"));

        colorSetSelector.setModel(getColorSetModel(ThemeManager.getSelectedTheme()));

        colorSetLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        colorSetLabel.setLabelFor(colorSetSelector);
        colorSetLabel.setText(Translate.text("themeColorSet"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(languageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(themeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colorSetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(themeSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(languageSelector, 0, 267, Short.MAX_VALUE)
                    .addComponent(colorSetSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(themeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorSetSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorSetLabel))
                .addContainerGap(204, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void themeSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeSelectorActionPerformed
        // TODO add your handling code here:
        String selectedThemeName = themeSelector.getSelectedItem().toString();
        ThemeManager.getThemes().stream().filter(info -> info.selectable).sorted(tc).filter(theme -> theme.getName().equals(selectedThemeName)).findFirst().ifPresent(ft -> {
            colorSetSelector.setModel(getColorSetModel(ft));
        });
    }//GEN-LAST:event_themeSelectorActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> colorSetSelector;
    private javax.swing.JComboBox<String> languageSelector;
    private javax.swing.JComboBox<String> themeSelector;
    // End of variables declaration//GEN-END:variables

}
