/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package artofillusion.preferences;

import artofillusion.ArtOfIllusion;
import artofillusion.ui.ThemeManager;
import artofillusion.ui.Translate;
import java.util.Comparator;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author MaksK
 */
@Slf4j
public class AppearancePreferencesPanelImpl extends javax.swing.JPanel {
    
    private static final Comparator<ThemeManager.ThemeInfo> tc  = Comparator.comparing(ThemeManager.ThemeInfo::getName);
    private final Locale[] languages = Translate.getAvailableLocales();
    /**
     * Creates new form AppearancePreferencesPanelImpl
     */
    public AppearancePreferencesPanelImpl() {
        initComponents();
    }

    private DefaultComboBoxModel getLocalesModel() {
        var dcm = new DefaultComboBoxModel();
        var cloc =  ArtOfIllusion.getPreferences().getLocale();
        for(Locale loc: languages) {
            var localeDisplayName = loc.getDisplayName(loc);
            dcm.addElement(localeDisplayName);
            if(cloc.equals(loc)) dcm.setSelectedItem(localeDisplayName);
        }
        return  dcm;
    } 
    
    private DefaultComboBoxModel getThemesModel() {
        var dcm = new DefaultComboBoxModel();
        var selectedThemeName = ThemeManager.getSelectedTheme().getName();
        ThemeManager.getThemes().stream().filter(info -> info.selectable).sorted(tc).forEach(theme -> {
            dcm.addElement(theme.getName());
            if(theme.getName().equals(selectedThemeName)) dcm.setSelectedItem(theme.getName());
        });
        return dcm;
    } 
            
    public Locale getSelectedLocale() {
        return languages[languageSelector.getSelectedIndex()];
    }

    public String getSelectedThemeName() {
        return jComboBox1.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languageSelector = new javax.swing.JComboBox<>();
        languageLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        languageSelector.setMaximumRowCount(languages.length > 20 ? 16 : languages.length);
        languageSelector.setModel(getLocalesModel());

        languageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        languageLabel.setLabelFor(languageSelector);
        languageLabel.setText(Translate.text("language"));

        jComboBox1.setModel(getThemesModel());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(Translate.text("selectedTheme"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(languageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(languageSelector, 0, 267, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel languageLabel;
    private javax.swing.JComboBox<String> languageSelector;
    // End of variables declaration//GEN-END:variables

}
