/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package artofillusion.preferences;

import artofillusion.ArtOfIllusion;
import artofillusion.ui.Translate;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author MaksK
 */
@Slf4j
public class AppearancePreferencesPanelImpl extends javax.swing.JPanel {
    private final Locale[] languages = Translate.getAvailableLocales();
    /**
     * Creates new form AppearancePreferencesPanelImpl
     */
    public AppearancePreferencesPanelImpl() {
        initComponents();
    }

    private DefaultComboBoxModel getLocalesModel() {
        var dcm = new DefaultComboBoxModel();
        var cloc =  ArtOfIllusion.getPreferences().getLocale();
        for(Locale loc: languages) {
            var localeDisplayName = loc.getDisplayName(loc);
            dcm.addElement(localeDisplayName);
            if(cloc.equals(loc)) dcm.setSelectedItem(localeDisplayName);
        }
        return  dcm;
    } 
    
    public Locale getSelectedLocale() {
        return languages[languageSelector.getSelectedIndex()];
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        languageSelector = new javax.swing.JComboBox<>();
        languageLabel = new javax.swing.JLabel();

        languageSelector.setMaximumRowCount(languages.length > 20 ? 16 : languages.length);
        languageSelector.setModel(getLocalesModel());

        languageLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        languageLabel.setLabelFor(languageSelector);
        languageLabel.setText(Translate.text("language"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(languageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(languageSelector, 0, 297, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageLabel))
                .addContainerGap(272, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel languageLabel;
    private javax.swing.JComboBox<String> languageSelector;
    // End of variables declaration//GEN-END:variables
}
