name: CheckStyle
on: []
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@v0.9.4
        with:
          reporter: github-pr-review
          level: warning
